print("- Encuentra una escoba y un recogedor adecuados para barrer.")
print("- Asegurate de que la habitacion este despejada de objetos grandes que puedan dificultar el barrido.")
print("- Toma la escoba con una mano en el mango y la otra en la parte superior del mango para tener un buen control.")
print("- Comienza desde una esquina de la habitacion y trabaja hacia afuera.")
print("- Si es posible, abre las ventanas para permitir que el polvo salga mientras barres.")
print("- Con movimientos largos y fluidos, barre el piso en direccion hacia ti.")
print("- Asegurate de cubrir toda la superficie, prestando especial atencion a las esquinas y debajo de los muebles.")
print("- Una vez que hayas barrido toda la habitacion, recoge la basura y los desechos con el recogedor.")
print("- Utiliza movimientos cuidadosos para evitar esparcir la suciedad nuevamente.")
print("- Vacia el contenido del recogedor en un contenedor de basura.")
print("- Sacude la escoba para quitar el polvo y los residuos atrapados en las cerdas.")
print("- Limpia el recogedor con un trapo humedo para eliminar cualquier suciedad restante.")