print("Bob: Hola! Como estas?")
print("Rob: Hola! Estoy bien, gracias. Y tu?")
print("Bob: Tambien estoy bien, gracias. Has visto el clima hoy?")
print("Rob: Si, parece que va a llover mas tarde.")
print("Bob: Si, he escuchado lo mismo. Esperemos que no sea muy fuerte.")
print("Rob: Has probado la comida en ese nuevo restaurante?")
print("Bob: No aun, que tal es?")
print("Rob: Es increible! Deberias probarlo.")
print("Bob: Definitivamente lo hare. Como va todo en el trabajo?")
print("Rob: Bastante ocupado ultimamente, pero bien en general. Y tu?")
print("Bob: Lo mismo por aqui, mucho trabajo pero todo bajo control.")
print("Rob: Has revisado tus finanzas recientemente?")
print("Bob: Si, estoy tratando de ahorrar mas este ano.")
print("Rob: Eso es genial, siempre es bueno tener un plan financiero.")
print("Bob: Si, definitivamente. Bueno, debo irme. Hasta luego!")
print("Rob: Hasta luego! Que tengas un buen dia.")